#!/bin/bash

docker run --rm -it                                                                                                     \
    --name "vending-machine-infection-execution"                                                                        \
    --network "vending-machine-net"                                                                                      \
    -v "${PWD}:/usr/src"                                                                                                \
    -w "/usr/src"                                                                                                       \
    -e "XDEBUG_MODE=coverage"                                                                                           \
    vending-machine.php-cli php vendor/bin/phpstan analyse src/$@