#!/bin/bash

docker run --rm -it                                                                                                     \
    --name "vending-machine-test-execution"                                                                             \
    --network "vending-machine-net"                                                                                      \
    -v "${PWD}:/usr/src"                                                                                                \
    -w "/usr/src"                                                                                                       \
    -e "XDEBUG_MODE=coverage"                                                                                           \
    vending-machine.php-cli php vendor/phpunit/phpunit/phpunit -d memory_limit=-1 --coverage-clover coverage.xml --coverage-html coverage --log-junit test.xml "$@"
